#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl8,  DRIVE,          sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ARM,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LDRIVE2,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           ARM1,          tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           ROLLER,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           MOGO,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ARM2,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           FB1,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FB2,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RDRIVE1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LDRIVE1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RDRIVE2,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int fullSpeed = 127;
int target = 0;
int gTarget = 0;
int aTarget = 0;
float kP = 3;
int kI = 100000;
float gKP = 3;
int gKI = 100000;
float aKP = 0.5;
int aKI = 10000;

float driveL() {
		return (vexRT[Ch3] + (vexRT[Ch1] * 1) * 1);
}

float driveR() {
		return (vexRT[Ch3] - (vexRT[Ch1] * 1) * 1);
}

void toggleM(int speed, int time, int freeze) {
	motor[MOGO] = speed;
	wait10Msec(time);
	motor[MOGO] = freeze;
}

void toggleFB(int speed, int time, int freeze) {
	motor[FB1] = -speed;
	motor[FB2] = -speed;
	wait10Msec(time);
	motor[FB1] = -freeze;
	motor[FB2] = -freeze;
}

void toggleRL(int speed, int time, int freeze) {
	motor[ROLLER] = speed;
	wait10Msec(time);
	motor[ROLLER] = freeze;
}

int getDriveSensor() {
	return -SensorValue[DRIVE];
}

int getGyroSensor() {
	return SensorValue[GYRO];
}

int getArmSensor() {
	return -SensorValue[ARM];
}

void setLDrive(int speed) {
	motor[LDRIVE1] = speed;
	motor[LDRIVE2] = speed;
}

void setRDrive(int speed) {
	motor[RDRIVE1] = speed;
	motor[RDRIVE2] = speed;
}

void setArm(int speed) {
	motor[ARM1] = speed;
	motor[ARM2] = speed;
}

void clearSensors() {
	SensorValue[DRIVE] = 0;
	SensorValue[GYRO] = 0;
	SensorValue[ARM] = 0;
}

task drivePID() {
	int totalError = 0;
	int lastError = getDriveSensor();
	int gTotalError = 0;
	int gLastError = getGyroSensor();

	while (true)
	{
		int currValue = getDriveSensor();
		int currError = currValue - target;
		int gCurrValue = getGyroSensor();
		int gCurrError = gCurrValue - gTarget;
		float currSpeedL = (currError / kP + totalError / kI) - (gCurrError / gKP + gTotalError / gKI);
		float currSpeedR = (currError / kP + totalError / kI) + (gCurrError / gKP + gTotalError / gKI);

		setLDrive(-currSpeedL);
		setRDrive(-currSpeedR);

		lastError = currError;
		gLastError = gCurrError;
		delay(20);
	}
}

task turnPID() {
	int gTotalError = 0;
	int gLastError = getGyroSensor();

	while (true)
	{
		int gCurrValue = getGyroSensor();
		int gCurrError = gCurrValue - gTarget;
		float currSpeedL = -(gCurrError / gKP + gTotalError / gKI);
		float currSpeedR = (gCurrError / gKP + gTotalError / gKI);

		setLDrive(-currSpeedL);
		setRDrive(-currSpeedR);

		gLastError = gCurrError;
		delay(20);
	}
}

task armPID() {
	int totalError = 0;
	int lastError = getArmSensor();

	while (true)
	{
		int currValue = getArmSensor();
		int currError = currValue - aTarget;
		float currSpeed = (currError / aKP + totalError / aKI);

		setArm(currSpeed);

		lastError = currError;
		delay(20);
	}
}

void skillsAuto() {
	kP = 15;
	clearSensors();
	gTarget = 0;
	aTarget = 600;
	target = 1750;
	startTask(armPID);
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(150);
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	target = 50;
	wait10Msec(175);
	stopTask(drivePID);
	gTarget = 300;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = -950;
	startTask(drivePID);
	wait10Msec(125);
	stopTask(drivePID);
	gTarget = 1075;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = getDriveSensor() + 2000;
	startTask(drivePID);
	wait10Msec(150);
	target = getDriveSensor() - 800;
	wait10Msec(125);
	stopTask(drivePID);
	gTarget = 1775;
	startTask(turnPID);
	wait10Msec(150);
	stopTask(turnPID);
	setLDrive(-40);
	setRDrive(-30);
	wait10Msec(325);
	setLDrive(0);
	setRDrive(0);
	wait10Msec(25);
	clearSensors();
	toggleM(fullSpeed, 75, 0);
	gTarget = 0;
	target = 1350;
	startTask(drivePID);
	wait10Msec(125);
	toggleM(-fullSpeed, 80, 0);
	wait10Msec(25);
	stopTask(drivePID);
	gTarget = -1060;
	startTask(turnPID);
	wait10Msec(125);
	stopTask(turnPID);
	target = 2000;
	startTask(drivePID);
	wait10Msec(150);
	kP = 5;
	toggleM(fullSpeed, 75, 0);
	wait10Msec(50);
	target = 1600;
	wait10Msec(60);
	toggleM(-fullSpeed, 75, 0);
	stopTask(drivePID);
	gTarget = -310;
	kP = 10;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	wait10Msec(25);
	target = 2500;
	startTask(drivePID);
	wait10Msec(125);
	toggleM(fullSpeed, 75, 0);
	stopTask(drivePID);
	gTarget = 415;
	startTask(turnPID);
	wait10Msec(110);
	stopTask(turnPID);
	target = 4000;
	startTask(drivePID);
	wait10Msec(100);
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(25);
	target = 3500;
	wait10Msec(100);
	stopTask(drivePID);
	gTarget = -1060;
	startTask(turnPID);
	wait10Msec(150);
	stopTask(turnPID);
	wait10Msec(25);
	target = 3850;
	startTask(drivePID);
	wait10Msec(100);
	toggleM(fullSpeed, 75, 0);
	wait10Msec(25);
	target = 3200;
	wait10Msec(25);
	toggleM(-fullSpeed, 80, 0);
	wait10Msec(20);
	stopTask(drivePID);
	gTarget = 435;
	startTask(turnPID);
	wait10Msec(175);
	stopTask(turnPID);
	target = 5800;
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(175);
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	target = getDriveSensor() + 900;
	wait10Msec(125);
	toggleM(fullSpeed, 75, 0);
}

void autoLeftTwoCone() {
	clearSensors();
	motor[ROLLER] = 10;
	gTarget = 0;
	aTarget = 600;
	target = 1650;
	startTask(armPID);
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(150);
	target = 1850;
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	aTarget = 30;
	wait10Msec(25);
	toggleRL(-fullSpeed, 50, 0);
	aTarget = 400;
	wait10Msec(50);
	toggleFB(fullSpeed, 50, 0);
	target = 2100;
	wait10Msec(75);
	motor[ROLLER] = 80;
	aTarget = 0;
	wait10Msec(125);
	motor[ROLLER] = 10;
	aTarget = 300;
	target = -200;
	wait10Msec(50);
	toggleFB(-fullSpeed, 125, 0);
	wait10Msec(50);
	toggleRL(-fullSpeed, 50, 0);
	wait10Msec(50);
	stopTask(drivePID);
	gTarget = 300;
	aTarget = 400;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = -1100;
	startTask(drivePID);
	wait10Msec(100);
	stopTask(drivePID);
	gTarget = 1075;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = getDriveSensor() + 2000;
	startTask(drivePID);
	wait10Msec(150);
	target = getDriveSensor() - 1000;
}

void autoLeftOneCone() {
	clearSensors();
	motor[ROLLER] = 10;
	gTarget = 0;
	aTarget = 600;
	target = 1650;
	startTask(armPID);
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(125);
	target = 1850;
	wait10Msec(25);
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	aTarget = 30;
	wait10Msec(25);
	toggleRL(-fullSpeed, 50, 0);
	aTarget = 400;
	wait10Msec(50);
	target = -200;
	wait10Msec(50);
	toggleRL(-fullSpeed, 50, 0);
	wait10Msec(50);
	stopTask(drivePID);
	gTarget = 300;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = -1100;
	startTask(drivePID);
	wait10Msec(100);
	stopTask(drivePID);
	gTarget = 1075;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = getDriveSensor() + 2000;
	startTask(drivePID);
	wait10Msec(150);
	target = getDriveSensor() - 1000;
	wait10Msec(125);
	stopTask(drivePID);
	gTarget = 1450;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	startTask(drivePID);
	target = getDriveSensor() - 2000;
}

void autoRightTwoCone() {
	clearSensors();
	motor[ROLLER] = 10;
	gTarget = 0;
	aTarget = 600;
	target = 1650;
	startTask(armPID);
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(150);
	target = 1850;
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	aTarget = 30;
	wait10Msec(25);
	toggleRL(-fullSpeed, 50, 0);
	aTarget = 400;
	wait10Msec(50);
	toggleFB(fullSpeed, 50, 0);
	target = 2100;
	wait10Msec(75);
	motor[ROLLER] = 80;
	aTarget = 0;
	wait10Msec(125);
	motor[ROLLER] = 10;
	aTarget = 350;
	target = -200;
	wait10Msec(50);
	toggleFB(-fullSpeed, 125, 0);
	wait10Msec(50);
	toggleRL(-fullSpeed, 50, 0);
	wait10Msec(50);
	stopTask(drivePID);
	gTarget = -300;
	aTarget = 400;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = -1250;
	startTask(drivePID);
	wait10Msec(100);
	stopTask(drivePID);
	gTarget = -1075;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = getDriveSensor() + 2000;
	startTask(drivePID);
	wait10Msec(150);
	target = getDriveSensor() - 1000;
}

void autoRightOneCone() {
	clearSensors();
	motor[ROLLER] = 10;
	gTarget = 0;
	aTarget = 600;
	target = 1650;
	startTask(armPID);
	wait10Msec(25);
	toggleM(fullSpeed, 75, 0);
	startTask(drivePID);
	wait10Msec(125);
	target = 1850;
	wait10Msec(25);
	toggleM(-fullSpeed, 90, 0);
	wait10Msec(50);
	aTarget = 30;
	wait10Msec(25);
	toggleRL(-fullSpeed, 50, 0);
	aTarget = 400;
	wait10Msec(50);
	target = -200;
	wait10Msec(50);
	toggleRL(-fullSpeed, 50, 0);
	wait10Msec(50);
	stopTask(drivePID);
	gTarget = -300;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = -1250;
	startTask(drivePID);
	wait10Msec(100);
	stopTask(drivePID);
	gTarget = -1075;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	target = getDriveSensor() + 2000;
	startTask(drivePID);
	wait10Msec(150);
	target = getDriveSensor() - 1000;
	stopTask(autonomous);
	wait10Msec(125);
	stopTask(drivePID);
	gTarget = 1450;
	startTask(turnPID);
	wait10Msec(100);
	stopTask(turnPID);
	startTask(drivePID);
	target = getDriveSensor() - 2000;
}

void autoPost() {
	clearSensors();
	motor[ROLLER] = 10;
	target = 400;
	wait10Msec(25);
	aTarget = 1100;
	startTask(armPID);
	wait10Msec(100);
	startTask(drivePID);
	toggleFB(fullSpeed, 50, 0);
	wait10Msec(75);
	aTarget = 750;
	wait10Msec(50);
	toggleRL(-fullSpeed, 100, 0);
	wait10Msec(25);
	aTarget = 1200;
	target = getDriveSensor() - 300;
	wait10Msec(75);
	stopTask(drivePID);
	gTarget = 600;
	startTask(turnPID);
	wait10Msec(125);
	stopTask(turnPID);
	wait10Msec(50);
	aTarget = 200;
	toggleM(fullSpeed, 75, 0);
	toggleFB(-fullSpeed, 75, 0);
	target = getDriveSensor() + 1800;
	startTask(drivePID);
	wait10Msec(300);
	stopTask(drivePID);
}

void pre_auton() {}

task autonomous() {
	skillsAuto();
}

task usercontrol() {
	while (true) {
		motor[LDRIVE1] = driveL();
		motor[LDRIVE2] = driveL();
		motor[RDRIVE1] = driveR();
		motor[RDRIVE2] = driveR();

		motor[MOGO] = vexRT[Btn6D] * fullSpeed + vexRT[Btn6U] * -fullSpeed;
		motor[ARM1] = -vexRT[Ch2Xmtr2] - 10;
		motor[ARM2] = -vexRT[Ch2Xmtr2] - 10;
		motor[FB1] = vexRT[Ch3Xmtr2];
		motor[FB2] = vexRT[Ch3Xmtr2];
		motor[ROLLER] = vexRT[Btn6DXmtr2] * -fullSpeed + vexRT[Btn6UXmtr2] * fullSpeed + 10;
	}
}
